### ISSUE TITLE
collect_data fails to collect with arbitrary config file

### ISSUE THREAD

**Issue by alec-hoyland** [alec-hoyland/tinnitus-reconstruction#13]
Hi Alec, 

So this is the command I am running,

>> [responses,stimuli]=collect_data('config','C:\Users\saman\OneDrive\Documents\GitHub\tinnitus-project\code\experiment\configs\config_custom.yaml')
![image](https://user-images.githubusercontent.com/30243182/157071511-7435e5e4-f758-480b-9cea-30117c02c55b.png)

And I have also attached the config file I am using. I had to go back and add the data_dir field so it could look in the correct place. I am also attaching what I am seeing in my data folder. 

**Config File**:

```yaml
subjectID: pilot&&subject=SJP&&stimuli_type=custom&&n_bins_filled_mean=20&&n_bins_filled_var=3
data_dir: '/home/alec/code/tinnitus-project/code/experiment/Data'
n_trials_per_block: 100
n_blocks: 10
total_trials: 1000
min_freq: 100
max_freq: 22000
n_bins: 100
n_bins_filled_mean: 20
```
